### PR TITLE
Verify using user-provided public key

### PR DESCRIPTION
**Pull request by Brcrwilliams**
The SSH signature verification implemented in https://github.com/github/ssh_data/pull/31 verifies the signature using the public key embedded in the signature itself. In practice, this means that `signature.verify(message)` behaves more like a complicated digest comparison than a signature, since we cannot use it to verify identity. For example, if we want to verify that a message was signed with [one of my SSH keys](https://github.com/brcrwilliams.keys), here's how I would expect that to work:

```ruby
require 'open-uri'
require 'ed25519'
require 'ssh_data'

def keys_for_user(username)
  URI("https://github.com/#{username}.keys").read.split("\n").map do |openssh|
    SSHData::PublicKey.parse_openssh(openssh)
  end
end

def user_key_with_fingerprint(username, fingerprint)
  keys_for_user(username).find do |key|
    key.fingerprint == fingerprint
  end
end

message = "This message was signed by @brcrwilliams on GitHub"
signature = <<~SIG
-----BEGIN SSH SIGNATURE-----
U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAgtc+Qk8jhMwVZk/jFEFCM16LNQb
30q5kK30bbetfjyTMAAAAEZmlsZQAAAAAAAAAGc2hhNTEyAAAAUwAAAAtzc2gtZWQyNTUx
OQAAAEDtDVzsf+wmSOhb3rfc8IutlcKGRX2RUX4gVWQzAET8jDOb6VKOCiWJYOE9hKWbrP
jGDzL3+ysPq8l4OIASa3kP
-----END SSH SIGNATURE-----
SIG

signature = SSHData::Signature.parse_pem(signature)
signed_by_fingerprint = signature.public_key.fingerprint
verification_key = user_key_with_fingerprint("brcrwilliams", signed_by_fingerprint)

if verification_key.nil?
  puts "User does not have a key with the fingerprint: #{signed_by_fingerprint}"
  return
end

puts "Verifying signature using key with fingerprint: #{verification_key.fingerprint}"

valid = signature.verify(verification_key, message)

if valid
  puts "Signature is valid"
else
  puts "Signature is not valid"
end
```

This message was signed using my SSH key pair with the public key `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILXPkJPI4TMFWZP4xRBQjNeizUG99KuZCt9G23rX48kz`.
If you run this code, you will get:

```
Verifying signature using key with fingerprint: Rl/cKcTkD030YGOZIY9bahcprPcHFoD2j1a5s0ytTFo
Signature is valid
```

Without providing an expected public key, anybody can re-sign the message with their own keys and `signature.verify(message)` will return true.

### CODE REVIEW

**Comment by Brcrwilliams** [comment]
@vcsjones @ptoomey3 Could you review this PR please? The tests are currently failing because there are some `ssh-rsa` keys in the fixtures, but before I go about trying to fix those I wanted to get your feedback and see if this PR would be accepted. This is a breaking change, but I think it's likely that any code using the previous implementation is likely not doing what the writer would expect it to do.

**Comment by ptoomey3** [comment]
I'll defer to @vcsjones since he is much more familiar with this code. But, curious if the following doesn't largely get you what you want:

``` ruby
require 'open-uri'
require 'ed25519'
require 'ssh_data'

def keys_for_user(username)
  URI("https://github.com/#{username}.keys").read.split("\n").map do |openssh|
    SSHData::PublicKey.parse_openssh(openssh)
  end
end

def user_key_with_fingerprint(username, fingerprint)
  keys_for_user(username).find do |key|
    key.fingerprint == fingerprint
  end
end

message = "This message was signed by @brcrwilliams on GitHub"
signature = <<~SIG
-----BEGIN SSH SIGNATURE-----
U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAgtc+Qk8jhMwVZk/jFEFCM16LNQb
30q5kK30bbetfjyTMAAAAEZmlsZQAAAAAAAAAGc2hhNTEyAAAAUwAAAAtzc2gtZWQyNTUx
OQAAAEDtDVzsf+wmSOhb3rfc8IutlcKGRX2RUX4gVWQzAET8jDOb6VKOCiWJYOE9hKWbrP
jGDzL3+ysPq8l4OIASa3kP
-----END SSH SIGNATURE-----
SIG

signature = SSHData::Signature.parse_pem(signature)
# We check to see if the signature is baseline well-formed/valid. 
# This only validates the owner of the associated private key made the signature.
# We haven't determined if we actually trust who/what the signature is associated with. 
valid_signature = signature.verify(message)
if valid_signature
  signed_by_fingerprint = signature.public_key.fingerprint
  verification_key = user_key_with_fingerprint("brcrwilliams", signed_by_fingerprint

  if verification_key.fingerprint == signature.public_key.fingerprint
    valid_key_for_author = true
  else
    valid_key_for_author = false
  end
end

# For a signature to be considered valid on GitHub.com we require a valid
# signature and for the key associated with that siganture to be associated
# with the author
valid = valid_signature && valid_key_for_author

if valid
  puts "Signature is valid"
else
  puts "Signature is not valid"
end
```

I'm not saying the API you proposed above maybe isn't a nice usability/convenience win for some scenarios I guess. But, I'm not sure it is needed for the most common scenarios.

**Comment by Brcrwilliams** [comment]
@ptoomey3 Thanks for the example. I see now that this is functionally about the same. Typically, I'd expect cryptographic APIs to perform all validation internally, so that it's difficult to use them incorrectly. However, I can see why you'd want to do it this way. It lets you avoid searching through keys if the signature isn't valid.

I'm interested to hear what @vcsjones thinks, but I'm ok with closing this PR.

I did some refactoring of the tests in this PR that I think would still be useful, so I've opened https://github.com/github/ssh_data/pull/36 for those changes.

**Comment by vcsjones** [comment]
Thanks for the pull request.

> @ptoomey3's example is the intended usage. However, I can see why you'd want to do it this way. It lets you avoid searching through keys if the signature isn't valid.

That's one reason. The other one is SSH certificates. With SSH certificates, we (GitHub) don't have certificates for individual users. All we have is a certificate authority. So the embedded key in signature is the only key we have. The verification for that would look like:

1. Check the signature (with internal certificate / key)
2. Get the certificate.
3. Make sure the certificate was issued by the SSH certificate authority that is trusted.
4. Make sure the certificate belongs to the user via some binding of attribute to user.

So while [this line](https://github.com/github/ssh_data/pull/35/files#diff-b87b83c6eb02dfe6ea6b38930dc3fd432862f5c70844fe721d1490902006195eR75) is functional, it makes the assumption that we have prior knowledge of a user's SSH certificate.


I'm going to hit close on this PR, but nonetheless thank you for the time you spent on this. I'll take a look at your other PR shortly.

**Pull request closed without merging**
